### ISSUE TITLE
Command to check PS LFC

### ISSUE THREAD

**Issue by intrepidsilence** [iamcanadian2222/MarantzIP#3]
Is it possible to create the command to check the status LFC with 'PS LFC ?' I tried to understand the structure of the project to use the 'write_command' function but failed. It would be great if there was a little more documentation on how to use your tool and what is implemented from the Denon/Marantz standard. 

Also, there is another project called 'homebridge-denon-tv' that is trying to figure out how to get all of the status requests working ('?'). He has some that work and some return no value, like this PS LFC ?. If you help he understand it here in your project I may be able to translate enough to help get it working in that project, too. 

Thanks in advance!

**Comment by tobiz** [comment]
I suggest taking a look at my MarantzAPI repository.  This includes a couple of scripts to test the API when called either from Python or C++.  
In general the "write_command" is used to call all functions other than those to assign the amp to different speaker configurations.  Take a look at "MarantzAPI_test.py", this shows how the two different commands are used.
As to your specific question I haven't tried "PS LFC ?" (this probably should be "PSLFC?", not PSLFC ?" or "PSLFC ON" not "PSLFCON") but can see no reason why it shouldn't work.  The Marantz Spec is not very good.
Also note some commands do not return any results, this seems to be a property of the Marantz command set and my Marantz NR1604 is really, really slow to respond.  It's a long time since I worked on this code and my own branch has probably moved on a long way.  At the moment I'm on pause since it does everything I want it to do.

This is the spec I worked to: 2013 Marantz_AV_SR_NR_PROTOCOL_V07.xls.  If you can't find it let me know and I'll paste it into a reply.

**Comment by intrepidsilence** [comment]
Yes, PSLCF? specifically is how it should be called according to the spec (I think, not terribly clear). I did not look at the spec you worked from but have read the latest version a few times. It does not really clarify or spell things out.  I do wonder why there would be a status command if it did not work. Also, how would the Marantz app work and get status if it does not work? Could it be using some proprietary API instead of the one they defined?

I noticed in the calls in your code there appears to be something regarding clearing a buffer before sending the new commands.  Is that internal to your code or something the Marantz needs? If something it needs, do you know why and how did you figure that out as I do not see it in the spec?

Thanks again. 

You mention your own branch is further ahead... any chance that you will be committing it to the public branch ever?

**Comment by intrepidsilence** [comment]
Also, could you point me to your MarantzAPI repo? I clicked your name in Github and did not see it among your 30 repos.

**Comment by tobiz** [comment]
Clearing the buffer before sending new commands is not internal to my code other than it makes it work.  I discovered it by trial and error and using various tools that enable you to sending data over a TCP/IP link at a basic level and seeing what is returned, this and a lot of guess work as to what might be happening came up with a working solution.  I have to say the IP command interface to the Marantz and its implementation in the H/W itself is some of the worst s/w engineering I've come across.  The old RS232C interface was much simpler and better defined.  However accessing and controlling the Marantz directly from a web browser is not too bad, it's as if they don't want you to work out how to write your own code so you can call it from your own app.  Working out how to control the Amp Assign functions took several weeks, the only solution I found was to emulate the http interface.

[https://github.com/tobiz/MarantzAPI](url) should get you there.

I will upload my latest branch sometime which is used my by work on a plugin for MythTV which includes controlling the Marantz AV Amp and a relay for raising and lowering the central ceiling speaker my setup has.  However I strongly suspect the MarantzAPI code I used is the one in my repository, although I did come across a few issues wrt Python2.7 vs Python3 when using it with my MythTV plugin.

**Comment by tobiz** [comment]
The version I use now is on tobiz/MarantzAPI.

**Comment by intrepidsilence** [comment]
Thanks much!
